services:
  
  frontend:
    image: node:18-alpine
    build:
      context: ./frontend
      dockerfile: ./frontend/Dockerfile
    ports:
      - "4400:4400"
    volumes:
      - ./frontend:/app    
    working_dir: /app/frontend
    depends_on:
      - strapi

  strapi:
    image: node:18-alpine
    build:
      context: ./strapi
      dockerfile: ./strapi/Dockerfile
    ports:
      - "4500:4500"
    volumes:
      - ./strapi:/app
    # depends_on:
    #   - db
    working_dir: /app/strapi

#   db:
#     image: mysql:8.0.36
#     # mysql 8:0.36 specified because native_password isn't supported in more recent versions.
#     restart: always
#     command: --default-authentication-plugin=mysql_native_password
#     environment:
#       MYSQL_DATABASE: strapi
#       MYSQL_ROOT_PASSWORD: 123
#     volumes:
#       - db-data:/var/lib/mysql
#     ports:
#       - 3396:3306

# volumes:
#   db-data: