services:
  frontend:
    build:
      context: .
      target: base-frontend
    command: yarn dev
    volumes:
      - ./:/app
    working_dir: /app/frontend
    environment:
      - NUXT_PUBLIC_API_ENDPOINT=http://0.0.0:4500
      - NUXT_PUBLIC_INTERNAL_API_ENDPOINT=http://strapi:4500
      # - NUXT_PUBLIC_API_ENDPOINT=https://api.smartshore.com
      # - NUXT_PUBLIC_INTERNAL_API_ENDPOINT=https://api.smartshore.com
      # - NUXT_PUBLIC_BASE_URL=https://smartshore.com
    depends_on:
      - strapi
    ports:
      - 4400:4400
      - 24678:24678

  strapi:
    build:
      context: .
      target: base-strapi
    command: yarn develop
    ports:
      - 4500:4500
    volumes:
      - ./:/app
    working_dir: /app/strapi